### ISSUE TITLE
osip_parse crash

### ISSUE THREAD

**Issue by defeden** [Distrotech/libosip2#1]
Hi;
i have this backtrace

#0  0x00007ffff71ddc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff71e1028 in __GI_abort () at abort.c:89
#2  0x00007ffff721a2a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff732c350 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff7225007 in malloc_printerr (action=<optimized out>, str=0x7ffff732c6f0 "malloc(): memory corruption (fast)", ptr=<optimized out>) at malloc.c:4998
#4  0x00007ffff722898f in _int_malloc (av=0x7ffff7569760 <main_arena>, bytes=4) at malloc.c:3361
#5  0x00007ffff7229ae0 in __GI___libc_malloc (bytes=4) at malloc.c:2893
#6  0x00007ffff7bb443e in osip_uri_parse (url=0x626df0, buf=0x625da0 "sip:asterisk@10.0.0.10:5060;transport=TCP") at osip_uri.c:118
#7  0x00007ffff7bb330d in osip_from_parse (from=0x627d70, hvalue=0x626b30 "<sip:asterisk@10.0.0.10:5060;transport=TCP>") at osip_from.c:236
#8  0x00007ffff7bc310b in osip_contact_parse (contact=0x627d70, hvalue=0x626b30 "<sip:asterisk@10.0.0.10:5060;transport=TCP>") at osip_contact.c:68
#9  0x00007ffff7bc304a in osip_message_set_contact (sip=0x626410, hvalue=0x626b30 "<sip:asterisk@10.0.0.10:5060;transport=TCP>") at osip_contact.c:42
#10 0x00007ffff7bc717a in __osip_message_call_method (i=10, dest=0x626410, hvalue=0x626b30 "<sip:asterisk@10.0.0.10:5060;transport=TCP>") at osip_parser_cfg.c:232
#11 0x00007ffff7bc159e in osip_message_set__header (sip=0x626410, hname=0x6278f0 "contact", hvalue=0x626b30 "<sip:asterisk@10.0.0.10:5060;transport=TCP>") at osip_message_parse.c:411
#12 0x00007ffff7bc190b in osip_message_set_multiple_header (sip=0x626410, hname=0x6278f0 "contact", hvalue=0x626b30 "<sip:asterisk@10.0.0.10:5060;transport=TCP>") at osip_message_parse.c:474
#13 0x00007ffff7bc2026 in msg_headers_parse (sip=0x626410, 
    start_of_header=0x627f97 "Contact: <sip:asterisk@10.0.0.10:5060;transport=TCP>\r\nMax-Forwards: 69\r\nCall-ID: 34d51ce77f4cf7070f4ff41b3ad89a2e@time-reversal.com\r\nCSeq: 102 NOTIFY\r\nUser-Agent: HPBX\r\nEve"..., 
    body=0x7fffffffd8e8) at osip_message_parse.c:665
#14 0x00007ffff7bc2b42 in _osip_message_parse (sip=0x626410, 
    buf=0x618230 "NOTIFY sip:perf-1000@10.0.1.11:56796 SIP/2.0\r\nVia: SIP/2.0/TCP 10.0.0.10:5060;branch=z9hG4bK7af6b6f969f2188981ea3d90c1c4e260\r\nVia: SIP/2.0/UDP 10.42.0.70:5060;branch=z9hG4bK2c941d44\r\nFrom: "..., length=701, sipfrag=0)
    at osip_message_parse.c:881
#15 0x00007ffff7bc2d36 in osip_message_parse (sip=0x626410, 
 buf=0x618230 "NOTIFY sip:perf-1000@10.0.1.11:56796 SIP/2.0\r\nVia: SIP/2.0/TCP 10.0.0.10:5060;branch=z9hG4bK7af6b6f969f2188981ea3d90c1c4e260\r\nVia: SIP/2.0/UDP 10.42.0.70:5060;branch=z9hG4bK2c941d44\r\nFrom: "..., length=701)
    at osip_message_parse.c:915
#16 0x00007ffff79a1c24 in osip_parse (
    buf=0x618230 "NOTIFY sip:perf-1000@10.0.1.11:56796 SIP/2.0\r\nVia: SIP/2.0/TCP 10.0.0.10:5060;branch=z9hG4bK7af6b6f969f2188981ea3d90c1c4e260\r\nVia: SIP/2.0/UDP 10.42.0.70:5060;branch=z9hG4bK2c941d44\r\nFrom: "..., length=701) at osip_event.c:43

**Comment by defeden** [comment]
it seems it is related to the use of osip_XXX_execute which calls kill cb, this will invalidate the transaction pointer, when returning from callback and using the transaction pointer it sucks.

can you make a good example on how to use libosip2 please?

**Comment by defeden** [comment]
i have an other segfault

#0  malloc_consolidate (av=av@entry=0x7ffff7569760 <main_arena>) at malloc.c:4153
#1  0x00007ffff72278b8 in _int_malloc (av=0x7ffff7569760 <main_arena>, bytes=4000) at malloc.c:3425
#2  0x00007ffff7229ae0 in __GI___libc_malloc (bytes=4000) at malloc.c:2893
#3  0x00007ffff7bc40d2 in _osip_message_to_str (sip=0x61d490, dest=0x7fffffffd8b0, message_length=0x7fffffffd8a8, sipfrag=0) at osip_message_to_str.c:431
#4  0x00007ffff7bc5d1f in osip_message_to_str (sip=0x61d490, dest=0x7fffffffd8b0, message_length=0x7fffffffd8a8) at osip_message_to_str.c:774
#5  0x0000000000404678 in peer_send (tr=0x61e360, sip=0x61d490, host=0x621590 "my-domain.com", port=5060, sock=0) at src/peer.c:218
#6  0x00007ffff799af8a in nict_snd_request (nict=0x61e360, evt=0x6215d0) at nict_fsm.c:119
#7  0x00007ffff799d232 in fsm_callmethod (type=SND_REQUEST, state=NICT_PRE_TRYING, statemachine=0x7ffff7ba7940 <nict_fsm>, sipevent=0x6215d0, transaction=0x61e360) at fsm_misc.c:53
#8  0x00007ffff79a0d63 in osip_transaction_execute (transaction=0x61e360, evt=0x6215d0) at osip_transaction.c:363
#9  0x000000000040632e in sip_execute (osip=0x612900) at src/sip.c:125
#10 0x0000000000408011 in on_peer_cb (loop=0x7ffff7993900, io=0x60fba0, revents=1) at src/scenario.c:201
#11 0x00007ffff7789e45 in ev_invoke_pending () from /usr/lib/x86_64-linux-gnu/libev.so.4
#12 0x00007ffff778cfe7 in ev_run () from /usr/lib/x86_64-linux-gnu/libev.so.4
#13 0x0000000000409571 in main (argc=3, argv=0x7fffffffdbb8) at src/sipsim.c:138
